package version

// Version is the canonical version string. Regenerated by scripts/release.sh
// on each release commit; overridden at build time via ldflags for dev builds.
var Version = "v1.2.3"

// Commit is the short SHA at build time. Empty when built from a tarball.
var Commit = "b3a7a41"

// Date is the RFC3339-UTC build timestamp. Empty when built from a tarball.
var Date = "2026-07-08T03:42:03Z"
