package version

// Version is the canonical version string. Regenerated by scripts/release.sh
// on each release commit; overridden at build time via ldflags for dev builds.
var Version = "v0.1.1"

// Commit is the short SHA at build time. Empty when built from a tarball.
var Commit = "2f870fd"

// Date is the RFC3339-UTC build timestamp. Empty when built from a tarball.
var Date = "2026-07-06T04:19:56Z"
