package version

// Version is the canonical version string. Default "dev"; overridden at build
// time via -ldflags "-X 'atm/internal/version.Version=...'". Regenerated by
// scripts/release.sh on each release commit.
var Version = "dev"

// Commit is the short SHA at build time. Empty when built from a tarball with
// no .git; the text formatter trims it from output in that case.
var Commit = ""

// Date is the RFC3339-UTC build timestamp. Empty when built from a tarball.
var Date = ""