#!/bin/sh
# Pure, sourceable POSIX sh helpers for the release pipeline. No side effects
# on source; functions exit non-zero on invalid input.
#
# This file is sourced by scripts/release.sh and tests/scripts/runner.sh.
# Do not execute it directly.

rel_VERSION_RE='^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-rc\.(0|[1-9][0-9]*))?$'

rel_version_validate() {
  v=$1
  [ -n "$v" ] || return 1
  printf '%s' "$v" | grep -Eq "$rel_VERSION_RE"
}

rel_version_strip_v() {
  v=$1
  printf '%s' "$v" | sed 's/^v//'
}

rel_next_rc() {
  v=$1
  case "$v" in
    *-rc.[0-9]*)
      base=${v%-rc.*}
      n=${v##*-rc.}
      printf '%s-rc.%d' "$base" "$((n + 1))"
      ;;
    *)
      printf '%s-rc.0' "$v"
      ;;
  esac
}

rel_target_matrix() {
  printf 'linux/amd64\nlinux/arm64\ndarwin/amd64\ndarwin/arm64\n'
}

rel_tarball_name() {
  v=$1; os=$2; arch=$3
  printf 'atm_%s_%s_%s.tar.gz' "$v" "$os" "$arch"
}

rel_sha_line() {
  hash=$1; file=$2
  printf '%s  %s\n' "$hash" "$file"
}

rel_git_dirty() {
  [ -n "$(git status --porcelain)" ]
}

rel_regen_version_go() {
  v=$1; commit=$2; date=$3; out=$4
  cat > "$out" <<EOF
package version

// Version is the canonical version string. Regenerated by scripts/release.sh
// on each release commit; overridden at build time via ldflags for dev builds.
var Version = "$v"

// Commit is the short SHA at build time. Empty when built from a tarball.
var Commit = "$commit"

// Date is the RFC3339-UTC build timestamp. Empty when built from a tarball.
var Date = "$date"
EOF
}