# Tests for rel_git_dirty and rel_regen_version_go (determinism).

EXPECTED_VERSION_GO='package version

// Version is the canonical version string. Regenerated by scripts/release.sh
// on each release commit; overridden at build time via ldflags for dev builds.
var Version = "v0.1.0"

// Commit is the short SHA at build time. Empty when built from a tarball.
var Commit = "abc1234"

// Date is the RFC3339-UTC build timestamp. Empty when built from a tarball.
var Date = "2026-07-06T00:00:00Z"'

test_git_dirty_clean() {
  tmp=$(mktemp -d)
  git init -q "$tmp"
  (cd "$tmp" && git config user.email t@t && git config user.name t && echo hi > f && git add f && git commit -qm x)
  if (cd "$tmp" && rel_git_dirty); then
    fails=$((fails + 1)); echo "FAIL: clean tree reported dirty"
  else
    passes=$((passes + 1))
  fi
  rm -rf "$tmp"
}

test_git_dirty_dirty() {
  tmp=$(mktemp -d)
  git init -q "$tmp"
  (cd "$tmp" && git config user.email t@t && git config user.name t && echo hi > f && git add f && git commit -qm x && echo bye > f)
  if (cd "$tmp" && rel_git_dirty); then
    passes=$((passes + 1))
  else
    fails=$((fails + 1)); echo "FAIL: dirty tree reported clean"
  fi
  rm -rf "$tmp"
}

test_regen_version_deterministic() {
  tmp=$(mktemp -d)
  rel_regen_version_go v0.1.0 abc1234 2026-07-06T00:00:00Z "$tmp/version.go"
  got=$(cat "$tmp/version.go")
  assert_eq "$got" "$EXPECTED_VERSION_GO" "regen output matches fixed expected"
  rel_regen_version_go v0.1.0 abc1234 2026-07-06T00:00:00Z "$tmp/version.go"
  got2=$(cat "$tmp/version.go")
  assert_eq "$got2" "$EXPECTED_VERSION_GO" "regen idempotent"
  rm -rf "$tmp"
}

test_preflight_version_valid() {
  assert_exit 0 rel_preflight_version v0.1.0
}
test_preflight_version_invalid() {
  assert_exit 1 rel_preflight_version v1.0.0-alpha
}
test_preflight_version_empty() {
  assert_exit 1 rel_preflight_version ""
}

test_git_dirty_clean
test_git_dirty_dirty
test_regen_version_deterministic
test_preflight_version_valid
test_preflight_version_invalid
test_preflight_version_empty